service: graphql-mongodb-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

custom:
  hooks:
    before:package:compileFunctions:
      commands: npm install
    before:deploy:runBuild:
      commands: npm run build

functions:
  graphql:
    handler: lambda/dist/graphql.handler
    timeout: 120
    events:
      - http:
          path: graphql
          method: post
          cors: true
